/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author jairo
 */
public class vistaCalculadora extends javax.swing.JFrame {

    JTextField [][] primeraMatriz;
    JTextField [][] segundaMatriz;
    JTextField [][] terceraMatriz;
    
    /**
     * Creates new form NewJFrame
     */
    public vistaCalculadora() {
        initComponents();
        this.OperacionSeleccionada.setVisible(false);
        this.getMatrizAPanel().setVisible(false);
        this.getMatrizBPanel().setVisible(false);
        this.getMatrizRPanel().setVisible(false);
        this.primeraMatriz = new JTextField[5][5];
        this.segundaMatriz = new JTextField[5][5];
        this.terceraMatriz = new JTextField[5][5];


        primeraMatriz[0][0] = this.matrizAcelda1;
        primeraMatriz[0][1] = this.matrizAcelda2;
        primeraMatriz[0][2] = this.matrizAcelda3;
        primeraMatriz[0][3] = this.matrizAcelda4;
        primeraMatriz[0][4] = this.matrizAcelda5;
        primeraMatriz[1][0] = this.matrizAcelda6;
        primeraMatriz[1][1] = this.matrizAcelda7;
        primeraMatriz[1][2] = this.matrizAcelda8;
        primeraMatriz[1][3] = this.matrizAcelda9;
        primeraMatriz[1][4] = this.matrizAcelda10;
        primeraMatriz[2][0] = this.matrizAcelda11;
        primeraMatriz[2][1] = this.matrizAcelda12;
        primeraMatriz[2][2] = this.matrizAcelda13;
        primeraMatriz[2][3] = this.matrizAcelda14;
        primeraMatriz[2][4] = this.matrizAcelda15;
        primeraMatriz[3][0] = this.matrizAcelda16;
        primeraMatriz[3][1] = this.matrizAcelda17;
        primeraMatriz[3][2] = this.matrizAcelda18;
        primeraMatriz[3][3] = this.matrizAcelda19;
        primeraMatriz[3][4] = this.matrizAcelda20;
        primeraMatriz[4][0] = this.matrizAcelda21;
        primeraMatriz[4][1] = this.matrizAcelda22;
        primeraMatriz[4][2] = this.matrizAcelda23;
        primeraMatriz[4][3] = this.matrizAcelda24;
        primeraMatriz[4][4] = this.matrizAcelda25; 

        segundaMatriz[0][0] = this.matrizBcelda1;
        segundaMatriz[0][1] = this.matrizBcelda2;
        segundaMatriz[0][2] = this.matrizBcelda3;
        segundaMatriz[0][3] = this.matrizBcelda4;
        segundaMatriz[0][4] = this.matrizBcelda5;
        segundaMatriz[1][0] = this.matrizBcelda6;
        segundaMatriz[1][1] = this.matrizBcelda7;
        segundaMatriz[1][2] = this.matrizBcelda8;
        segundaMatriz[1][3] = this.matrizBcelda9;
        segundaMatriz[1][4] = this.matrizBcelda10;
        segundaMatriz[2][0] = this.matrizBcelda11;
        segundaMatriz[2][1] = this.matrizBcelda12;
        segundaMatriz[2][2] = this.matrizBcelda13;
        segundaMatriz[2][3] = this.matrizBcelda14;
        segundaMatriz[2][4] = this.matrizBcelda15;
        segundaMatriz[3][0] = this.matrizBcelda16;
        segundaMatriz[3][1] = this.matrizBcelda17;
        segundaMatriz[3][2] = this.matrizBcelda18;
        segundaMatriz[3][3] = this.matrizBcelda19;
        segundaMatriz[3][4] = this.matrizBcelda20;
        segundaMatriz[4][0] = this.matrizBcelda21;
        segundaMatriz[4][1] = this.matrizBcelda22;
        segundaMatriz[4][2] = this.matrizBcelda23;
        segundaMatriz[4][3] = this.matrizBcelda24;
        segundaMatriz[4][4] = this.matrizBcelda25;

        terceraMatriz[0][0] = this.matrizResCelda1;
        terceraMatriz[0][1] = this.matrizResCelda2;
        terceraMatriz[0][2] = this.matrizResCelda3;
        terceraMatriz[0][3] = this.matrizResCelda4;
        terceraMatriz[0][4] = this.matrizResCelda5;
        terceraMatriz[1][0] = this.matrizResCelda6;
        terceraMatriz[1][1] = this.matrizResCelda7;
        terceraMatriz[1][2] = this.matrizResCelda8;
        terceraMatriz[1][3] = this.matrizResCelda9;
        terceraMatriz[1][4] = this.matrizResCelda10;
        terceraMatriz[2][0] = this.matrizResCelda11;
        terceraMatriz[2][1] = this.matrizResCelda12;
        terceraMatriz[2][2] = this.matrizResCelda13;
        terceraMatriz[2][3] = this.matrizResCelda14;
        terceraMatriz[2][4] = this.matrizResCelda15;
        terceraMatriz[3][0] = this.matrizResCelda16;
        terceraMatriz[3][1] = this.matrizResCelda17;
        terceraMatriz[3][2] = this.matrizResCelda18;
        terceraMatriz[3][3] = this.matrizResCelda19;
        terceraMatriz[3][4] = this.matrizResCelda20;
        terceraMatriz[4][0] = this.matrizResCelda21;
        terceraMatriz[4][1] = this.matrizResCelda22;
        terceraMatriz[4][2] = this.matrizResCelda23;
        terceraMatriz[4][3] = this.matrizResCelda24;
        terceraMatriz[4][4] = this.matrizResCelda25;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        metodoGauss = new javax.swing.JButton();
        multiplicarMatrices = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        escalar = new javax.swing.JTextField();
        multiplicaEscalar = new javax.swing.JButton();
        inversa = new javax.swing.JButton();
        determinante = new javax.swing.JButton();
        MatrizAPanel = new javax.swing.JPanel();
        matrizAcelda1 = new javax.swing.JTextField();
        matrizAcelda2 = new javax.swing.JTextField();
        matrizAcelda3 = new javax.swing.JTextField();
        matrizAcelda4 = new javax.swing.JTextField();
        matrizAcelda5 = new javax.swing.JTextField();
        matrizAcelda6 = new javax.swing.JTextField();
        matrizAcelda7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        matrizAcelda10 = new javax.swing.JTextField();
        matrizAcelda11 = new javax.swing.JTextField();
        matrizAcelda12 = new javax.swing.JTextField();
        matrizAcelda13 = new javax.swing.JTextField();
        matrizAcelda14 = new javax.swing.JTextField();
        matrizAcelda15 = new javax.swing.JTextField();
        matrizAcelda16 = new javax.swing.JTextField();
        matrizAcelda17 = new javax.swing.JTextField();
        matrizAcelda18 = new javax.swing.JTextField();
        matrizAcelda22 = new javax.swing.JTextField();
        matrizAcelda23 = new javax.swing.JTextField();
        matrizAcelda24 = new javax.swing.JTextField();
        matrizAcelda25 = new javax.swing.JTextField();
        matrizAcelda8 = new javax.swing.JTextField();
        matrizAcelda9 = new javax.swing.JTextField();
        matrizAcelda19 = new javax.swing.JTextField();
        matrizAcelda20 = new javax.swing.JTextField();
        matrizAcelda21 = new javax.swing.JTextField();
        MatrizBPanel = new javax.swing.JPanel();
        matrizBcelda10 = new javax.swing.JTextField();
        matrizBcelda11 = new javax.swing.JTextField();
        matrizBcelda12 = new javax.swing.JTextField();
        matrizBcelda13 = new javax.swing.JTextField();
        matrizBcelda14 = new javax.swing.JTextField();
        matrizBcelda15 = new javax.swing.JTextField();
        matrizBcelda19 = new javax.swing.JTextField();
        matrizBcelda7 = new javax.swing.JTextField();
        matrizBcelda20 = new javax.swing.JTextField();
        matrizBcelda21 = new javax.swing.JTextField();
        matrizBcelda22 = new javax.swing.JTextField();
        matrizBcelda5 = new javax.swing.JTextField();
        matrizBcelda6 = new javax.swing.JTextField();
        matrizBcelda8 = new javax.swing.JTextField();
        matrizBcelda9 = new javax.swing.JTextField();
        matrizBcelda16 = new javax.swing.JTextField();
        matrizBcelda1 = new javax.swing.JTextField();
        matrizBcelda2 = new javax.swing.JTextField();
        matrizBcelda3 = new javax.swing.JTextField();
        matrizBcelda4 = new javax.swing.JTextField();
        matrizBcelda25 = new javax.swing.JTextField();
        matrizBcelda17 = new javax.swing.JTextField();
        matrizBcelda18 = new javax.swing.JTextField();
        matrizBcelda23 = new javax.swing.JTextField();
        matrizBcelda24 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MatrizRPanel = new javax.swing.JPanel();
        matrizResCelda25 = new javax.swing.JTextField();
        matrizResCelda22 = new javax.swing.JTextField();
        matrizResCelda23 = new javax.swing.JTextField();
        matrizResCelda10 = new javax.swing.JTextField();
        matrizResCelda11 = new javax.swing.JTextField();
        matrizResCelda20 = new javax.swing.JTextField();
        matrizResCelda14 = new javax.swing.JTextField();
        matrizResCelda15 = new javax.swing.JTextField();
        matrizResCelda16 = new javax.swing.JTextField();
        matrizResCelda17 = new javax.swing.JTextField();
        matrizResCelda18 = new javax.swing.JTextField();
        matrizResCelda19 = new javax.swing.JTextField();
        matrizResCelda24 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        matrizResCelda13 = new javax.swing.JTextField();
        matrizResCelda12 = new javax.swing.JTextField();
        matrizResCelda2 = new javax.swing.JTextField();
        matrizResCelda3 = new javax.swing.JTextField();
        matrizResCelda4 = new javax.swing.JTextField();
        matrizResCelda5 = new javax.swing.JTextField();
        matrizResCelda1 = new javax.swing.JTextField();
        matrizResCelda6 = new javax.swing.JTextField();
        matrizResCelda7 = new javax.swing.JTextField();
        matrizResCelda8 = new javax.swing.JTextField();
        matrizResCelda21 = new javax.swing.JTextField();
        matrizResCelda9 = new javax.swing.JTextField();
        CalcularButton = new javax.swing.JButton();
        OperacionSeleccionada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        columnasA = new javax.swing.JTextField();
        filasA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        columnasB = new javax.swing.JTextField();
        filasB = new javax.swing.JTextField();
        mostrarMatrizA = new javax.swing.JButton();
        mostrarMatrizB = new javax.swing.JButton();
        cramer = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        metodoGauss.setText("Gauss-Jordan");

        multiplicarMatrices.setText("Multiplicar");

        suma.setText("Sumar");

        multiplicaEscalar.setText("Multiplicar por:");

        inversa.setText("Inversa");

        determinante.setText("Determinante");

        matrizAcelda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda1ActionPerformed(evt);
            }
        });

        matrizAcelda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda2ActionPerformed(evt);
            }
        });

        matrizAcelda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Matriz A");

        matrizAcelda10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda10ActionPerformed(evt);
            }
        });

        matrizAcelda12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda12ActionPerformed(evt);
            }
        });

        matrizAcelda17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda17ActionPerformed(evt);
            }
        });

        matrizAcelda18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda18ActionPerformed(evt);
            }
        });

        matrizAcelda24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda24ActionPerformed(evt);
            }
        });

        matrizAcelda8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda8ActionPerformed(evt);
            }
        });

        matrizAcelda19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizAcelda19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MatrizAPanelLayout = new javax.swing.GroupLayout(MatrizAPanel);
        MatrizAPanel.setLayout(MatrizAPanelLayout);
        MatrizAPanelLayout.setHorizontalGroup(
            MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizAPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MatrizAPanelLayout.createSequentialGroup()
                        .addComponent(matrizAcelda16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizAPanelLayout.createSequentialGroup()
                        .addComponent(matrizAcelda11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizAPanelLayout.createSequentialGroup()
                        .addComponent(matrizAcelda21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizAcelda25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(MatrizAPanelLayout.createSequentialGroup()
                            .addComponent(matrizAcelda6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MatrizAPanelLayout.createSequentialGroup()
                            .addComponent(matrizAcelda1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizAcelda5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(MatrizAPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1))
        );
        MatrizAPanelLayout.setVerticalGroup(
            MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizAPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizAcelda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizAcelda6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizAcelda11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizAcelda16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizAcelda21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizAcelda25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        matrizBcelda10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizBcelda10ActionPerformed(evt);
            }
        });

        matrizBcelda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizBcelda1ActionPerformed(evt);
            }
        });

        matrizBcelda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizBcelda2ActionPerformed(evt);
            }
        });

        matrizBcelda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizBcelda4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Matriz B");

        javax.swing.GroupLayout MatrizBPanelLayout = new javax.swing.GroupLayout(MatrizBPanel);
        MatrizBPanel.setLayout(MatrizBPanelLayout);
        MatrizBPanelLayout.setHorizontalGroup(
            MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizBPanelLayout.createSequentialGroup()
                .addGroup(MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MatrizBPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MatrizBPanelLayout.createSequentialGroup()
                                .addComponent(matrizBcelda6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MatrizBPanelLayout.createSequentialGroup()
                                .addComponent(matrizBcelda11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MatrizBPanelLayout.createSequentialGroup()
                                .addComponent(matrizBcelda16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MatrizBPanelLayout.createSequentialGroup()
                                .addComponent(matrizBcelda21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MatrizBPanelLayout.createSequentialGroup()
                                .addComponent(matrizBcelda1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matrizBcelda5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MatrizBPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)))
                .addGap(10, 10, 10))
        );
        MatrizBPanelLayout.setVerticalGroup(
            MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizBPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizBcelda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizBcelda6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizBcelda11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizBcelda16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizBcelda21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizBcelda25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        matrizResCelda14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizResCelda14ActionPerformed(evt);
            }
        });

        jLabel3.setText("Matriz resultado");

        matrizResCelda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizResCelda2ActionPerformed(evt);
            }
        });

        matrizResCelda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizResCelda4ActionPerformed(evt);
            }
        });

        matrizResCelda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizResCelda5ActionPerformed(evt);
            }
        });

        matrizResCelda6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizResCelda6ActionPerformed(evt);
            }
        });

        matrizResCelda9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizResCelda9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MatrizRPanelLayout = new javax.swing.GroupLayout(MatrizRPanel);
        MatrizRPanel.setLayout(MatrizRPanelLayout);
        MatrizRPanelLayout.setHorizontalGroup(
            MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizRPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MatrizRPanelLayout.createSequentialGroup()
                        .addComponent(matrizResCelda21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizRPanelLayout.createSequentialGroup()
                        .addComponent(matrizResCelda16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizRPanelLayout.createSequentialGroup()
                        .addComponent(matrizResCelda11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizRPanelLayout.createSequentialGroup()
                        .addComponent(matrizResCelda6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MatrizRPanelLayout.createSequentialGroup()
                        .addComponent(matrizResCelda1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizResCelda5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MatrizRPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(96, 96, 96))
        );
        MatrizRPanelLayout.setVerticalGroup(
            MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrizRPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizResCelda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizResCelda6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizResCelda11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizResCelda16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrizRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrizResCelda21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrizResCelda25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CalcularButton.setText("Calcular");

        OperacionSeleccionada.setText("Operacion");

        jLabel4.setText("Dimensiones de la matriz A:");

        columnasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnasAActionPerformed(evt);
            }
        });

        filasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasAActionPerformed(evt);
            }
        });

        jLabel5.setText("Dimensiones de la matriz B:");

        columnasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnasBActionPerformed(evt);
            }
        });

        mostrarMatrizA.setText("Mostrar");
        mostrarMatrizA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMatrizAActionPerformed(evt);
            }
        });

        mostrarMatrizB.setText("Mostrar");
        mostrarMatrizB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMatrizBActionPerformed(evt);
            }
        });

        cramer.setText("Cramer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(MatrizAPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(MatrizBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(MatrizRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filasA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columnasA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarMatrizA)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(filasB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columnasB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarMatrizB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplicarMatrices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(metodoGauss)
                        .addGap(18, 18, 18)
                        .addComponent(cramer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(determinante)
                            .addComponent(multiplicaEscalar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escalar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inversa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CalcularButton)))
                .addGap(18, 18, 18)
                .addComponent(OperacionSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inversa)
                    .addComponent(determinante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicaEscalar)
                    .addComponent(escalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suma)
                    .addComponent(multiplicarMatrices)
                    .addComponent(metodoGauss)
                    .addComponent(cramer))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(filasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(columnasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(filasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(columnasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarMatrizA)
                    .addComponent(mostrarMatrizB))
                .addGap(18, 18, 18)
                .addComponent(MatrizAPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalcularButton)
                    .addComponent(OperacionSeleccionada))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MatrizRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(MatrizBPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matrizAcelda18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda18ActionPerformed

    private void matrizAcelda17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda17ActionPerformed

    private void matrizAcelda24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda24ActionPerformed

    private void matrizResCelda9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizResCelda9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizResCelda9ActionPerformed

    private void matrizResCelda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizResCelda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizResCelda4ActionPerformed

    private void matrizAcelda19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda19ActionPerformed

    private void matrizResCelda14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizResCelda14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizResCelda14ActionPerformed

    private void matrizAcelda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda2ActionPerformed

    private void matrizAcelda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda1ActionPerformed

    private void matrizAcelda10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda10ActionPerformed

    private void columnasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnasAActionPerformed

    private void columnasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnasBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnasBActionPerformed

    private void matrizAcelda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda4ActionPerformed

    private void matrizAcelda8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda8ActionPerformed

    private void matrizAcelda12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizAcelda12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizAcelda12ActionPerformed

    private void matrizResCelda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizResCelda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizResCelda2ActionPerformed

    private void matrizResCelda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizResCelda5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizResCelda5ActionPerformed

    private void matrizResCelda6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizResCelda6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizResCelda6ActionPerformed

    private void mostrarMatrizAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMatrizAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarMatrizAActionPerformed

    private void mostrarMatrizBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMatrizBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarMatrizBActionPerformed

    private void filasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filasAActionPerformed

    private void matrizBcelda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizBcelda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizBcelda4ActionPerformed

    private void matrizBcelda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizBcelda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizBcelda2ActionPerformed

    private void matrizBcelda10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizBcelda10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizBcelda10ActionPerformed

    private void matrizBcelda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizBcelda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizBcelda1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCalculadora().setVisible(true);
            }
        });
    }

    public JLabel getOperacionSeleccionada() {
        return OperacionSeleccionada;
    }

    public JPanel getMatrizAPanel() {
        return MatrizAPanel;
    }

    public JPanel getMatrizBPanel() {
        return MatrizBPanel;
    }

    public JPanel getMatrizRPanel() {
        return MatrizRPanel;
    }

    public JTextField[][] getPrimeraMatriz() {
        return primeraMatriz;
    }

    public JTextField[][] getSegundaMatriz() {
        return segundaMatriz;
    }

    public JTextField[][] getTerceraMatriz() {
        return terceraMatriz;
    }

    public JButton getCramer() {
        return cramer;
    }
    
    

    public JTextField getColumnasA() {
        return columnasA;
    }

    public JTextField getColumnasB() {
        return columnasB;
    }

    public JButton getDeterminante() {
        return determinante;
    }

    public JTextField getEscalar() {
        return escalar;
    }

    public JTextField getFilasA() {
        return filasA;
    }

    public JTextField getFilasB() {
        return filasB;
    }

    public JButton getInversa() {
        return inversa;
    }

    public JButton getMetodoGauss() {
        return metodoGauss;
    }

    public JButton getMultiplicarMatrices() {
        return multiplicarMatrices;
    }

    public JButton getMultiplicaEscalar() {
        return multiplicaEscalar;
    }

    public JButton getSuma() {
        return suma;
    }

    public JButton getCalcularButton() {
        return CalcularButton;
    }

    public JButton getMostrarMatrizA() {
        return mostrarMatrizA;
    }

    public JButton getMostrarMatrizB() {
        return mostrarMatrizB;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularButton;
    private javax.swing.JPanel MatrizAPanel;
    private javax.swing.JPanel MatrizBPanel;
    private javax.swing.JPanel MatrizRPanel;
    private javax.swing.JLabel OperacionSeleccionada;
    private javax.swing.JTextField columnasA;
    private javax.swing.JTextField columnasB;
    private javax.swing.JButton cramer;
    private javax.swing.JButton determinante;
    private javax.swing.JTextField escalar;
    private javax.swing.JTextField filasA;
    private javax.swing.JTextField filasB;
    private javax.swing.JButton inversa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matrizAcelda1;
    private javax.swing.JTextField matrizAcelda10;
    private javax.swing.JTextField matrizAcelda11;
    private javax.swing.JTextField matrizAcelda12;
    private javax.swing.JTextField matrizAcelda13;
    private javax.swing.JTextField matrizAcelda14;
    private javax.swing.JTextField matrizAcelda15;
    private javax.swing.JTextField matrizAcelda16;
    private javax.swing.JTextField matrizAcelda17;
    private javax.swing.JTextField matrizAcelda18;
    private javax.swing.JTextField matrizAcelda19;
    private javax.swing.JTextField matrizAcelda2;
    private javax.swing.JTextField matrizAcelda20;
    private javax.swing.JTextField matrizAcelda21;
    private javax.swing.JTextField matrizAcelda22;
    private javax.swing.JTextField matrizAcelda23;
    private javax.swing.JTextField matrizAcelda24;
    private javax.swing.JTextField matrizAcelda25;
    private javax.swing.JTextField matrizAcelda3;
    private javax.swing.JTextField matrizAcelda4;
    private javax.swing.JTextField matrizAcelda5;
    private javax.swing.JTextField matrizAcelda6;
    private javax.swing.JTextField matrizAcelda7;
    private javax.swing.JTextField matrizAcelda8;
    private javax.swing.JTextField matrizAcelda9;
    private javax.swing.JTextField matrizBcelda1;
    private javax.swing.JTextField matrizBcelda10;
    private javax.swing.JTextField matrizBcelda11;
    private javax.swing.JTextField matrizBcelda12;
    private javax.swing.JTextField matrizBcelda13;
    private javax.swing.JTextField matrizBcelda14;
    private javax.swing.JTextField matrizBcelda15;
    private javax.swing.JTextField matrizBcelda16;
    private javax.swing.JTextField matrizBcelda17;
    private javax.swing.JTextField matrizBcelda18;
    private javax.swing.JTextField matrizBcelda19;
    private javax.swing.JTextField matrizBcelda2;
    private javax.swing.JTextField matrizBcelda20;
    private javax.swing.JTextField matrizBcelda21;
    private javax.swing.JTextField matrizBcelda22;
    private javax.swing.JTextField matrizBcelda23;
    private javax.swing.JTextField matrizBcelda24;
    private javax.swing.JTextField matrizBcelda25;
    private javax.swing.JTextField matrizBcelda3;
    private javax.swing.JTextField matrizBcelda4;
    private javax.swing.JTextField matrizBcelda5;
    private javax.swing.JTextField matrizBcelda6;
    private javax.swing.JTextField matrizBcelda7;
    private javax.swing.JTextField matrizBcelda8;
    private javax.swing.JTextField matrizBcelda9;
    private javax.swing.JTextField matrizResCelda1;
    private javax.swing.JTextField matrizResCelda10;
    private javax.swing.JTextField matrizResCelda11;
    private javax.swing.JTextField matrizResCelda12;
    private javax.swing.JTextField matrizResCelda13;
    private javax.swing.JTextField matrizResCelda14;
    private javax.swing.JTextField matrizResCelda15;
    private javax.swing.JTextField matrizResCelda16;
    private javax.swing.JTextField matrizResCelda17;
    private javax.swing.JTextField matrizResCelda18;
    private javax.swing.JTextField matrizResCelda19;
    private javax.swing.JTextField matrizResCelda2;
    private javax.swing.JTextField matrizResCelda20;
    private javax.swing.JTextField matrizResCelda21;
    private javax.swing.JTextField matrizResCelda22;
    private javax.swing.JTextField matrizResCelda23;
    private javax.swing.JTextField matrizResCelda24;
    private javax.swing.JTextField matrizResCelda25;
    private javax.swing.JTextField matrizResCelda3;
    private javax.swing.JTextField matrizResCelda4;
    private javax.swing.JTextField matrizResCelda5;
    private javax.swing.JTextField matrizResCelda6;
    private javax.swing.JTextField matrizResCelda7;
    private javax.swing.JTextField matrizResCelda8;
    private javax.swing.JTextField matrizResCelda9;
    private javax.swing.JButton metodoGauss;
    private javax.swing.JButton mostrarMatrizA;
    private javax.swing.JButton mostrarMatrizB;
    private javax.swing.JButton multiplicaEscalar;
    private javax.swing.JButton multiplicarMatrices;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
