/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Matriz;
import javax.swing.JOptionPane;

/**
 *
 * @author dado0
 */
public class Interface extends javax.swing.JPanel {
    private Matriz matrizA;
    private Matriz matrizB;
    private Matriz matrizResultado;
    
    public static void main(String[] args)
    {
        new Interface();
    }
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSuma = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonMultiplica = new javax.swing.JButton();
        botonIngresarA = new javax.swing.JButton();
        botonIngresarB = new javax.swing.JButton();
        botonDeterminanteA = new javax.swing.JButton();
        botonTranspuestaA = new javax.swing.JButton();
        filasA = new javax.swing.JTextField();
        columnasA = new javax.swing.JTextField();
        filasB = new javax.swing.JTextField();
        columnasB = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonInversaA = new javax.swing.JButton();
        resultadoDetA = new javax.swing.JTextField();
        resultadoTransA = new javax.swing.JTextField();
        resultadoInversaA = new javax.swing.JTextField();
        botonDeterminanteB = new javax.swing.JButton();
        botonTranspuestaB = new javax.swing.JButton();
        botonInversaB = new javax.swing.JButton();
        resultadoDetB = new javax.swing.JTextField();
        resultadoInversaB = new javax.swing.JTextField();
        resultadoTransB = new javax.swing.JTextField();
        cajaResultados = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cuadroEscalar = new javax.swing.JTextField();
        resultadosMatrizA = new javax.swing.JTextField();
        resultadosMatrizB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botomMultEscalar = new javax.swing.JButton();
        botonGaussJordan = new javax.swing.JToggleButton();

        botonSuma.setText("Suma");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });

        botonResta.setText("Resta");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });

        botonMultiplica.setText("Multiplica");
        botonMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicaActionPerformed(evt);
            }
        });

        botonIngresarA.setText("Ingresar matriz A");
        botonIngresarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarAActionPerformed(evt);
            }
        });

        botonIngresarB.setText("ingresar matriz B");
        botonIngresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarBActionPerformed(evt);
            }
        });

        botonDeterminanteA.setText("Determinante A");
        botonDeterminanteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeterminanteAActionPerformed(evt);
            }
        });

        botonTranspuestaA.setText("Transpuesta A");
        botonTranspuestaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTranspuestaAActionPerformed(evt);
            }
        });

        filasA.setText("jTextField1");
        filasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasAActionPerformed(evt);
            }
        });

        columnasA.setText("jTextField2");
        columnasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnasAActionPerformed(evt);
            }
        });

        filasB.setText("jTextField3");

        columnasB.setText("jTextField4");

        a.setText("jTextField5");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        b.setText("jTextField6");

        jLabel1.setText("Filas Matriz A");

        jLabel2.setText("Columnas Matriz A");

        jLabel3.setText("Filas Matriz B");

        jLabel4.setText("Columnas Matriz B");

        botonInversaA.setText("Inversa A");

        resultadoDetA.setText("jTextField7");
        resultadoDetA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoDetAActionPerformed(evt);
            }
        });

        resultadoTransA.setText("jTextField8");
        resultadoTransA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTransAActionPerformed(evt);
            }
        });

        resultadoInversaA.setText("jTextField9");
        resultadoInversaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoInversaAActionPerformed(evt);
            }
        });

        botonDeterminanteB.setText("Determinante B");
        botonDeterminanteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeterminanteBActionPerformed(evt);
            }
        });

        botonTranspuestaB.setText("Transpuesta B");
        botonTranspuestaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTranspuestaBActionPerformed(evt);
            }
        });

        botonInversaB.setText("Inversa B");

        resultadoDetB.setText("jTextField10");
        resultadoDetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoDetBActionPerformed(evt);
            }
        });

        resultadoInversaB.setText("jTextField11");

        resultadoTransB.setText("jTextField12");

        cajaResultados.setText("jTextField1");

        jTextField3.setText("jTextField3");

        jLabel5.setText("Escalar:");

        cuadroEscalar.setText("jTextField1");
        cuadroEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroEscalarActionPerformed(evt);
            }
        });

        resultadosMatrizA.setText("jTextField2");

        resultadosMatrizB.setText("jTextField4");

        jLabel6.setText("Matriz A");

        jLabel7.setText("Matriz B");

        botomMultEscalar.setText("Multiplicar");
        botomMultEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botomMultEscalarActionPerformed(evt);
            }
        });

        botonGaussJordan.setText("Inversa Gauss-Jordan");
        botonGaussJordan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGaussJordanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultadoInversaA, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultadoInversaB, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(258, 258, 258)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(filasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addGap(36, 36, 36)
                                                .addComponent(filasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(botonDeterminanteA)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(resultadoDetA, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(resultadoTransA, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(resultadoTransB, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(botonInversaA)
                                        .addGap(169, 169, 169)
                                        .addComponent(botonInversaB)))
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cuadroEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botomMultEscalar)
                                        .addGap(200, 200, 200))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(resultadosMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resultadosMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(224, 224, 224))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(columnasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(columnasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(144, 144, 144)
                                        .addComponent(cajaResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(botonTranspuestaA)
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonDeterminanteB)
                                        .addComponent(resultadoDetB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonTranspuestaB)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(botonIngresarA)
                                .addGap(81, 81, 81)
                                .addComponent(botonIngresarB)
                                .addGap(205, 205, 205)
                                .addComponent(botonSuma)
                                .addGap(38, 38, 38)
                                .addComponent(botonResta)
                                .addGap(33, 33, 33)
                                .addComponent(botonMultiplica)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonGaussJordan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)))
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(filasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(columnasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(columnasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIngresarA)
                    .addComponent(botonIngresarB)
                    .addComponent(botonSuma)
                    .addComponent(botonResta)
                    .addComponent(botonMultiplica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDeterminanteA)
                    .addComponent(botonDeterminanteB)
                    .addComponent(jLabel5)
                    .addComponent(cuadroEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botomMultEscalar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultadoDetA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadosMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resultadoDetB)
                        .addComponent(resultadosMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTranspuestaA)
                    .addComponent(botonTranspuestaB)
                    .addComponent(botonGaussJordan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoTransA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoTransB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInversaA)
                    .addComponent(botonInversaB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoInversaB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoInversaA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filasAActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        // TODO add your handling code here:
        matrizResultado.setFilas(matrizA.getFilas());
        matrizResultado.setColumnas(matrizA.getColumnas());
        double[][] resultadoSuma = matrizResultado.sumaMatrices(matrizA.getM(),matrizB.getM());
        Matriz matrizResultadoSuma = new Matriz();
        for(int filas = 0; filas<resultadoSuma.length; filas++){
            for(int columnas = 0; columnas<resultadoSuma.length; columnas++){
                matrizResultadoSuma.insertar(filas, columnas, resultadoSuma[filas][columnas]);
            }
        }
        resultadoDetA.setText(matrizResultadoSuma.imprimir());
        cajaResultados.setText(matrizResultadoSuma.imprimir());
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicaActionPerformed
        // TODO add your handling code here:
        matrizResultado.setFilas(matrizA.getFilas());
        matrizResultado.setColumnas(matrizA.getColumnas());
        double[][] resultadoMultiplicacion = matrizResultado.multiplicacion(matrizA.getM(),matrizB.getM());
        Matriz matrizResultadoMultiA = new Matriz();
        for(int filas = 0; filas<resultadoMultiplicacion.length; filas++){
            for(int columnas = 0; columnas<resultadoMultiplicacion.length; columnas++){
                matrizResultadoMultiA.insertar(filas, columnas, resultadoMultiplicacion[filas][columnas]);
            }
        }
        cajaResultados.setText(matrizResultadoMultiA.imprimir());
    }//GEN-LAST:event_botonMultiplicaActionPerformed

    private void botonIngresarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarAActionPerformed
        // TODO add your handling code here:
        int filas = Integer.parseInt(filasA.getText());
        int columnas = Integer.parseInt(columnasA.getText());
        
        matrizA = new Matriz(filas, columnas);
        
        for(int i = 0; i<filas; i++){
            for(int j = 0; j<columnas; j++){
                int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un número para la posición [" +i+","+j+"]"));
                matrizA.insertar(filas, columnas, dato);
            }
        }
        a.setText(matrizA.imprimir());
    }//GEN-LAST:event_botonIngresarAActionPerformed

    private void botonIngresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarBActionPerformed
        // TODO add your handling code here:
        int filas = Integer.parseInt(filasB.getText());
        int columnas = Integer.parseInt(columnasB.getText());
        
        matrizB = new Matriz(filas, columnas);
        
        for(int i = 0; i<filas; i++){
            for(int j = 0; j<columnas; j++){
                int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un número para la posición [" +i+","+j+"]"));
                matrizB.insertar(filas, columnas, dato);
            }
        }
        b.setText(matrizB.imprimir());
    }//GEN-LAST:event_botonIngresarBActionPerformed

    private void botonTranspuestaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTranspuestaAActionPerformed
        // TODO add your handling code here:
        double[][] resultadoTranspuesta = matrizA.transpuesta(matrizA.getM());
        Matriz matrizResultadoTransA = new Matriz();
        for(int filas = 0; filas<resultadoTranspuesta.length; filas++){
            for(int columnas = 0; columnas<resultadoTranspuesta.length; columnas++){
                matrizResultadoTransA.insertar(filas, columnas, resultadoTranspuesta[filas][columnas]);
            }
        }
        resultadoDetA.setText(matrizResultadoTransA.imprimir());
    }//GEN-LAST:event_botonTranspuestaAActionPerformed

    private void botonDeterminanteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeterminanteBActionPerformed
        // TODO add your handling code here:
        double resultadoDetereminante = matrizB.calcularDeterminante(matrizB.getM());
        resultadoDetB.setText(String.valueOf(resultadoDetereminante));
    }//GEN-LAST:event_botonDeterminanteBActionPerformed

    private void columnasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnasAActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
        matrizResultado.setFilas(matrizA.getFilas());
        matrizResultado.setColumnas(matrizA.getColumnas());
        double[][] resultadoResta = matrizResultado.restaMatrices(matrizA.getM(),matrizB.getM());
        Matriz matrizResultadoResta = new Matriz();
        for(int filas = 0; filas<resultadoResta.length; filas++){
            for(int columnas = 0; columnas<resultadoResta.length; columnas++){
                matrizResultadoResta.insertar(filas, columnas, resultadoResta[filas][columnas]);
            }
        }
        cajaResultados.setText(matrizResultadoResta.imprimir());
    }//GEN-LAST:event_botonRestaActionPerformed

    private void resultadoDetAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoDetAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoDetAActionPerformed

    private void resultadoTransAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTransAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTransAActionPerformed

    private void resultadoDetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoDetBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoDetBActionPerformed

    private void resultadoInversaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoInversaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoInversaAActionPerformed

    private void botonDeterminanteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeterminanteAActionPerformed
        // TODO add your handling code here:
        
        double resultadoDetereminante = matrizA.calcularDeterminante(matrizA.getM());
        resultadoDetA.setText(String.valueOf(resultadoDetereminante));
    }//GEN-LAST:event_botonDeterminanteAActionPerformed

    private void botonTranspuestaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTranspuestaBActionPerformed
        // TODO add your handling code here:
        double[][] resultadoTranspuesta = matrizB.transpuesta(matrizB.getM());
        Matriz matrizResultadoTransB = new Matriz();
        for(int filas = 0; filas<resultadoTranspuesta.length; filas++){
            for(int columnas = 0; columnas<resultadoTranspuesta.length; columnas++){
                matrizResultadoTransB.insertar(filas, columnas, resultadoTranspuesta[filas][columnas]);
            }
        }
        resultadoDetA.setText(matrizResultadoTransB.imprimir());
    }//GEN-LAST:event_botonTranspuestaBActionPerformed

    private void botonGaussJordanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGaussJordanActionPerformed
        // TODO add your handling code here:
        double[][] resultadoGaussB = matrizB.matrizInversaGaussJordan(matrizB.getM());
        Matriz matrizResultadoGaussB = new Matriz();
        for(int filas = 0; filas<resultadoGaussB.length; filas++){
            for(int columnas = 0; columnas<resultadoGaussB.length; columnas++){
                matrizResultadoGaussB.insertar(filas, columnas, resultadoGaussB[filas][columnas]);
            }
        }
        resultadosMatrizB.setText(matrizResultadoGaussB.imprimir());
        
        double[][] resultadoGaussA = matrizA.matrizInversaGaussJordan(matrizA.getM());
        Matriz matrizResultadoGaussA = new Matriz();
        for(int filas = 0; filas<resultadoGaussB.length; filas++){
            for(int columnas = 0; columnas<resultadoGaussA.length; columnas++){
                matrizResultadoGaussA.insertar(filas, columnas, resultadoGaussA[filas][columnas]);
            }
        }
        resultadosMatrizA.setText(matrizResultadoGaussA.imprimir());
    }//GEN-LAST:event_botonGaussJordanActionPerformed

    private void botomMultEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botomMultEscalarActionPerformed
        // TODO add your handling code here:
        double escalar = Integer.parseInt(cuadroEscalar.getText());
        Matriz matrizResultadoEscalarA = new Matriz();
        double[][] resultadoMultEscalarA = matrizA.multiplicarEscalar(escalar, matrizA.getM());
        for(int filas = 0; filas<resultadoMultEscalarA.length; filas++){
            for(int columnas = 0; columnas<resultadoMultEscalarA.length; columnas++){
                matrizResultadoEscalarA.insertar(filas, columnas, resultadoMultEscalarA[filas][columnas]);
            }
        }
        resultadosMatrizA.setText(matrizResultadoEscalarA.imprimir());
        
        Matriz matrizResultadoEscalarB = new Matriz();
        double[][] resultadoMultEscalarB = matrizB.multiplicarEscalar(escalar, matrizB.getM());
        for(int filas = 0; filas<resultadoMultEscalarB.length; filas++){
            for(int columnas = 0; columnas<resultadoMultEscalarB.length; columnas++){
                matrizResultadoEscalarB.insertar(filas, columnas, resultadoMultEscalarB[filas][columnas]);
            }
        }
        resultadosMatrizB.setText(matrizResultadoEscalarB.imprimir());
        
    }//GEN-LAST:event_botomMultEscalarActionPerformed

    private void cuadroEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroEscalarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroEscalarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JButton botomMultEscalar;
    private javax.swing.JButton botonDeterminanteA;
    private javax.swing.JButton botonDeterminanteB;
    private javax.swing.JToggleButton botonGaussJordan;
    private javax.swing.JButton botonIngresarA;
    private javax.swing.JButton botonIngresarB;
    private javax.swing.JButton botonInversaA;
    private javax.swing.JButton botonInversaB;
    private javax.swing.JButton botonMultiplica;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSuma;
    private javax.swing.JButton botonTranspuestaA;
    private javax.swing.JButton botonTranspuestaB;
    private javax.swing.JTextField cajaResultados;
    private javax.swing.JTextField columnasA;
    private javax.swing.JTextField columnasB;
    private javax.swing.JTextField cuadroEscalar;
    private javax.swing.JTextField filasA;
    private javax.swing.JTextField filasB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField resultadoDetA;
    private javax.swing.JTextField resultadoDetB;
    private javax.swing.JTextField resultadoInversaA;
    private javax.swing.JTextField resultadoInversaB;
    private javax.swing.JTextField resultadoTransA;
    private javax.swing.JTextField resultadoTransB;
    private javax.swing.JTextField resultadosMatrizA;
    private javax.swing.JTextField resultadosMatrizB;
    // End of variables declaration//GEN-END:variables
}
